nome = input('Digite algo ')
print(type(nome))
print('É alfa numero? ',nome.isalnum())
print('Esta em maiusculo? ',nome.isupper())
print('É um numero? ',nome.isnumeric())
print('Esta em minusculo? ',nome.islower())